version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.8.0
    steps:
      - checkout
      - run: 
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  lint:
    docker:
      - image: circleci/node:11.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run: npm run lint
workflows:
  version: 2
  linting:
    jobs:
      - build
      - lint:
          requires:
            - build
